In [22]:
import numpy as np

### Numpy 的数组对象ndarray

In [ ]:
# . 表示浮点数类型
a = np.array([[1,2],[-1.,-2.]])

In [ ]:
a.dtype

In [ ]:
a.itemsize

创建

In [ ]:
np.arange(5)

In [ ]:
a = np.full([2,3], 1.)

In [ ]:
b1 = a.tolist()

b2 = list(a)

In [ ]:
x = np.full([2,3], 'a')
y = np.full_like(x, 100)

In [ ]:
# 注意观察间距和元素个数,未给出元素个数的默认为 50 个元素
l1 = np.linspace(1, 5, 5)
l2 = np.linspace(1, 5, 5, endpoint=False)
print(f"默认包含最后一个数：{l1}")
print(f"不包含最后一个数(endpoint=False)：{l2}")

数据文件的读取

In [ ]:
a = np.arange(100).reshape(5, 20)
# np.savetxt('a.csv', a,  delimiter=',')
np.savetxt('a.csv', a, fmt='%.1f', delimiter=',')

任意维度数据文件的写入和读取

In [ ]:
b = np.arange(100).reshape(5, 10, 2)
# a.tofile('b.dat',  format='%d') #二进制形式读取
a.tofile('b.dat', sep=',', format='%d')

随机函数

In [23]:
# [100, 200) --> shape(8, )
a = np.random.randint(100, 200, (8,))

In [25]:
# 元素的值越大，抽取的值越高
np.random.choice(a, (3,2), p = a / np.sum(a))

array([[184, 190],
       [190, 175],
       [123, 175]])

In [26]:
# 抽取时是否重用元素
np.random.choice(a, (3,2), replace=False)

array([[175, 184],
       [127, 123],
       [184, 190]])

统计函数

In [27]:
c = np.arange(15).reshape(3, 5)
# 权重与对应数相乘，最后除以总权重
np.average(c, axis=0, weights=[10, 5, 1])

array([2.1875, 3.1875, 4.1875, 5.1875, 6.1875])

In [33]:
print(f"数组c为: \n {c}")
c1 = np.mean(c, axis=1)
print(f"数组在axis=1的平均值为 \n {c1}")

数组c为: 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
数组在axis=1的平均值为 
 [ 2.  7. 12.]


梯度函数

In [43]:
d = np.random.randint(0, 20, (5))
print("原数组为{0}".format(d))
#计算方法
# -3 = (前一个-后一个)/2=(1 - 7) /2
# 最后一个元素：(当前-上一个)/2= (12 - 10)/1
np.gradient(d)

原数组为[ 7  6  1 10 12]


array([-1. , -3. ,  2. ,  5.5,  2. ])

In [44]:
# 多维数组梯度
e = np.random.randint(0, 50, (3,5))
# 返回 2 个数组，第一个数组为第一维度的梯度值，第二个数组为第二个维度的梯度值
np.gradient(e)

[array([[-32. ,  36. ,  -9. ,  22. ,  -2. ],
        [ -8.5,  11.5,  13.5,  11.5,  -3. ],
        [ 15. , -13. ,  36. ,   1. ,  -4. ]]),
 array([[-31. , -16. ,  -2. ,  13.5,  30. ],
        [ 37. ,  -4.5,  -9. ,  17. ,   6. ],
        [  9. ,   6. ,  -2. ,  -3. ,   1. ]])]